# Generated by Django 4.1.5 on 2023-01-15 21:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Максимум 250 символів', max_length=250, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публікації')),
                ('slug', models.SlugField(unique_for_date='pub_date', verbose_name='Слаг')),
                ('main_page', models.BooleanField(default=False, help_text='Показувати на головній сторінці', verbose_name='Головна')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='blog.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Стаття',
                'verbose_name_plural': 'Статті',
                'ordering': ['-pub_date'],
            },
        ),
    ]
